Update GH Actions (#2)

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,4 +1,4 @@
-name: Checks
+name: Tests
 
 on:
   push:
@@ -12,7 +12,7 @@ on:
 
 jobs:
 
-  check-syntax:
+  check-php-syntax:
     name: PHP ${{ matrix.php-version }} Syntax
     runs-on: ubuntu-latest
     strategy:
@@ -38,17 +38,44 @@ jobs:
         with:
           fail-on-warnings: true
 
+  check-development-leftovers:
+    name: Check Development Leftovers
+    runs-on: ubuntu-latest
+    steps:
+      -
+        name: Checkout
+        uses: actions/checkout@v4
+      -
+        name: Search for debugger or xdebug_break
+        run: |
+          echo "Scanning for 'debugger' or 'xdebug_break'..."
+          matches=$(grep -Enr --include=\*.{js,php} '(^|[^a-zA-Z0-9_])(debugger|xdebug_break)\b' . || true)
+          if [[ -n "$matches" ]]; then
+            echo "Found the following matches:"
+            echo "$matches"
+            echo "::error::Development leftovers found in the codebase."
+            exit 1
+          else
+            echo "No development leftovers found."
+          fi
+
   check-install:
     name: Install on Concrete ${{ matrix.ccm-version }}
     runs-on: ubuntu-latest
     container: ghcr.io/concrete5-community/docker5:${{ matrix.ccm-version }}
+    needs:
+      - check-php-syntax
+      - check-development-leftovers
     strategy:
       matrix:
         ccm-version:
           - 8.5.2
+          - "8.5"
           - "9.0"
           - "9.1"
           - "9.2"
+          - "9.3"
+          - "9.4"
           - latest
     steps:
       -
